
const DEFAULT_CONNECTION_ENCODING = "UTF-8"
const DEFAULT_CONNECTION_NENCODING = "UTF-8"
const SUPPORTED_CONNECTION_ENCODINGS = ("ASCII", "UTF-8")

const ORA_MAJOR_VERSION = UInt32(3)
const ORA_MINOR_VERSION = UInt32(1)
const ORA_PATCH_LEVEL = UInt32(0)
const ORA_DEFAULT_FETCH_ARRAY_SIZE = UInt32(100)
const ORA_DEFAULT_PING_INTERVAL = UInt32(60)
const ORA_DEFAULT_PING_TIMEOUT = UInt32(5000)
const ORA_DEQ_WAIT_NO_WAIT = UInt32(0)
const ORA_MAX_INT64_PRECISION = UInt32(18)
