
const DPI_MAJOR_VERSION = UInt32(3)
const DPI_MINOR_VERSION = UInt32(0)
const DPI_PATCH_LEVEL = UInt32(0)
const DPI_DEFAULT_FETCH_ARRAY_SIZE = UInt32(100)
const DPI_DEFAULT_PING_INTERVAL = UInt32(60)
const DPI_DEFAULT_PING_TIMEOUT = UInt32(5000)
const DPI_DEQ_WAIT_NO_WAIT = UInt32(0)
const DPI_MAX_INT64_PRECISION = UInt32(18)

@static if VERSION < v"0.7-"

    @enum dpiResult::Int32 DPI_SUCCESS=0 DPI_FAILURE=-1
    @enum dpiAuthMode::UInt32 DPI_MODE_AUTH_DEFAULT=0 DPI_MODE_AUTH_SYSDBA=2 DPI_MODE_AUTH_SYSOPER=4 DPI_MODE_AUTH_PRELIM=8 DPI_MODE_AUTH_SYSASM=32768 DPI_MODE_AUTH_SYSBKP=131072 DPI_MODE_AUTH_SYSDGD=262144 DPI_MODE_AUTH_SYSKMT=524288 DPI_MODE_AUTH_SYSRAC=1048576
    @enum dpiConnCloseMode::UInt32 DPI_MODE_CONN_CLOSE_DEFAULT=0 DPI_MODE_CONN_CLOSE_DROP=1 DPI_MODE_CONN_CLOSE_RETAG=2
    @enum dpiCreateMode::UInt32 DPI_MODE_CREATE_DEFAULT=0 DPI_MODE_CREATE_THREADED=1 DPI_MODE_CREATE_EVENTS=4
    @enum dpiPoolGetMode::UInt32 DPI_MODE_POOL_GET_WAIT=0 DPI_MODE_POOL_GET_NOWAIT=1 DPI_MODE_POOL_GET_FORCEGET=2 DPI_MODE_POOL_GET_TIMEDWAIT=3
    @enum dpiPurity::UInt32 DPI_PURITY_DEFAULT=0 DPI_PURITY_NEW=1 DPI_PURITY_SELF=2
    @enum dpiShutdownMode::UInt32 DPI_MODE_SHUTDOWN_DEFAULT=0 DPI_MODE_SHUTDOWN_TRANSACTIONAL=1 DPI_MODE_SHUTDOWN_TRANSACTIONAL_LOCAL=2 DPI_MODE_SHUTDOWN_IMMEDIATE=3 DPI_MODE_SHUTDOWN_ABORT=4 DPI_MODE_SHUTDOWN_FINAL=5
    @enum dpiStartupMode::UInt32 DPI_MODE_STARTUP_DEFAULT=0 DPI_MODE_STARTUP_FORCE=1 DPI_MODE_STARTUP_RESTRICT=2
    @enum dpiExecMode::UInt32 DPI_MODE_EXEC_DEFAULT=0 DPI_MODE_EXEC_DESCRIBE_ONLY=16 DPI_MODE_EXEC_COMMIT_ON_SUCCESS=32 DPI_MODE_EXEC_BATCH_ERRORS=128 DPI_MODE_EXEC_PARSE_ONLY=256 DPI_MODE_EXEC_ARRAY_DML_ROWCOUNTS=1048576
    @enum dpiOracleTypeNum::UInt32 DPI_ORACLE_TYPE_NONE=2000 DPI_ORACLE_TYPE_VARCHAR=2001 DPI_ORACLE_TYPE_NVARCHAR=2002 DPI_ORACLE_TYPE_CHAR=2003 DPI_ORACLE_TYPE_NCHAR=2004 DPI_ORACLE_TYPE_ROWID=2005 DPI_ORACLE_TYPE_RAW=2006 DPI_ORACLE_TYPE_NATIVE_FLOAT=2007 DPI_ORACLE_TYPE_NATIVE_DOUBLE=2008 DPI_ORACLE_TYPE_NATIVE_INT=2009 DPI_ORACLE_TYPE_NUMBER=2010 DPI_ORACLE_TYPE_DATE=2011 DPI_ORACLE_TYPE_TIMESTAMP=2012 DPI_ORACLE_TYPE_TIMESTAMP_TZ=2013 DPI_ORACLE_TYPE_TIMESTAMP_LTZ=2014 DPI_ORACLE_TYPE_INTERVAL_DS=2015 DPI_ORACLE_TYPE_INTERVAL_YM=2016 DPI_ORACLE_TYPE_CLOB=2017 DPI_ORACLE_TYPE_NCLOB=2018 DPI_ORACLE_TYPE_BLOB=2019 DPI_ORACLE_TYPE_BFILE=2020 DPI_ORACLE_TYPE_STMT=2021 DPI_ORACLE_TYPE_BOOLEAN=2022 DPI_ORACLE_TYPE_OBJECT=2023 DPI_ORACLE_TYPE_LONG_VARCHAR=2024 DPI_ORACLE_TYPE_LONG_RAW=2025 DPI_ORACLE_TYPE_NATIVE_UINT=2026 DPI_ORACLE_TYPE_MAX=2027
    @enum dpiNativeTypeNum::UInt32 DPI_NATIVE_TYPE_INT64=3000 DPI_NATIVE_TYPE_UINT64=3001 DPI_NATIVE_TYPE_FLOAT=3002 DPI_NATIVE_TYPE_DOUBLE=3003 DPI_NATIVE_TYPE_BYTES=3004 DPI_NATIVE_TYPE_TIMESTAMP=3005 DPI_NATIVE_TYPE_INTERVAL_DS=3006 DPI_NATIVE_TYPE_INTERVAL_YM=3007 DPI_NATIVE_TYPE_LOB=3008 DPI_NATIVE_TYPE_OBJECT=3009 DPI_NATIVE_TYPE_STMT=3010 DPI_NATIVE_TYPE_BOOLEAN=3011 DPI_NATIVE_TYPE_ROWID=3012
    @enum dpiStatementType::UInt16 DPI_STMT_TYPE_UNKNOWN=0 DPI_STMT_TYPE_SELECT=1 DPI_STMT_TYPE_UPDATE=2 DPI_STMT_TYPE_DELETE=3 DPI_STMT_TYPE_INSERT=4 DPI_STMT_TYPE_CREATE=5 DPI_STMT_TYPE_DROP=6 DPI_STMT_TYPE_ALTER=7 DPI_STMT_TYPE_BEGIN=8 DPI_STMT_TYPE_DECLARE=9 DPI_STMT_TYPE_CALL=10 DPI_STMT_TYPE_EXPLAIN_PLAN=15 DPI_STMT_TYPE_MERGE=16 DPI_STMT_TYPE_ROLLBACK=17 DPI_STMT_TYPE_COMMIT=21

else

    @enum dpiResult::Int32 begin
        DPI_SUCCESS = 0
        DPI_FAILURE = -1
    end

    """
    This enumeration identifies the mode to use when authorizing connections to the database.
    """
    @enum dpiAuthMode::UInt32 begin
        DPI_MODE_AUTH_DEFAULT = 0
        DPI_MODE_AUTH_SYSDBA  = 2
        DPI_MODE_AUTH_SYSOPER = 4
        DPI_MODE_AUTH_PRELIM  = 8
        DPI_MODE_AUTH_SYSASM  = 32768
        DPI_MODE_AUTH_SYSBKP  = 131072
        DPI_MODE_AUTH_SYSDGD  = 262144
        DPI_MODE_AUTH_SYSKMT  = 524288
        DPI_MODE_AUTH_SYSRAC  = 1048576
    end

    @enum dpiConnCloseMode::UInt32 begin
        DPI_MODE_CONN_CLOSE_DEFAULT = 0
        DPI_MODE_CONN_CLOSE_DROP    = 1
        DPI_MODE_CONN_CLOSE_RETAG   = 2
    end

    """
    This enumeration identifies the mode to use when creating connections to the database. Note that the OCI objects mode is always enabled.
    """
    @enum dpiCreateMode::UInt32 begin
        DPI_MODE_CREATE_DEFAULT  = 0
        DPI_MODE_CREATE_THREADED = 1
        DPI_MODE_CREATE_EVENTS   = 4
    end

    """
    This enumeration identifies the mode to use when getting sessions from a session pool.
    """
    @enum dpiPoolGetMode::UInt32 begin
        DPI_MODE_POOL_GET_WAIT      = 0
        DPI_MODE_POOL_GET_NOWAIT    = 1
        DPI_MODE_POOL_GET_FORCEGET  = 2
        DPI_MODE_POOL_GET_TIMEDWAIT = 3
    end

    """
    This enumeration identifies the purity of the sessions that are acquired when using connection classes during connection creation.
    """
    @enum dpiPurity::UInt32 begin
        DPI_PURITY_DEFAULT = 0
        DPI_PURITY_NEW     = 1
        DPI_PURITY_SELF    = 2
    end

    @enum dpiShutdownMode::UInt32 begin
        DPI_MODE_SHUTDOWN_DEFAULT             = 0
        DPI_MODE_SHUTDOWN_TRANSACTIONAL       = 1
        DPI_MODE_SHUTDOWN_TRANSACTIONAL_LOCAL = 2
        DPI_MODE_SHUTDOWN_IMMEDIATE           = 3
        DPI_MODE_SHUTDOWN_ABORT               = 4
        DPI_MODE_SHUTDOWN_FINAL               = 5
    end

    @enum dpiStartupMode::UInt32 begin
        DPI_MODE_STARTUP_DEFAULT  = 0
        DPI_MODE_STARTUP_FORCE    = 1
        DPI_MODE_STARTUP_RESTRICT = 2
    end

    @enum dpiExecMode::UInt32 begin
        DPI_MODE_EXEC_DEFAULT             = 0
        DPI_MODE_EXEC_DESCRIBE_ONLY       = 16
        DPI_MODE_EXEC_COMMIT_ON_SUCCESS   = 32
        DPI_MODE_EXEC_BATCH_ERRORS        = 128
        DPI_MODE_EXEC_PARSE_ONLY          = 256
        DPI_MODE_EXEC_ARRAY_DML_ROWCOUNTS = 1048576
    end

    @enum dpiOracleTypeNum::UInt32 begin
        DPI_ORACLE_TYPE_NONE          = 2000
        DPI_ORACLE_TYPE_VARCHAR       = 2001
        DPI_ORACLE_TYPE_NVARCHAR      = 2002
        DPI_ORACLE_TYPE_CHAR          = 2003
        DPI_ORACLE_TYPE_NCHAR         = 2004
        DPI_ORACLE_TYPE_ROWID         = 2005
        DPI_ORACLE_TYPE_RAW           = 2006
        DPI_ORACLE_TYPE_NATIVE_FLOAT  = 2007
        DPI_ORACLE_TYPE_NATIVE_DOUBLE = 2008
        DPI_ORACLE_TYPE_NATIVE_INT    = 2009
        DPI_ORACLE_TYPE_NUMBER        = 2010
        DPI_ORACLE_TYPE_DATE          = 2011
        DPI_ORACLE_TYPE_TIMESTAMP     = 2012
        DPI_ORACLE_TYPE_TIMESTAMP_TZ  = 2013
        DPI_ORACLE_TYPE_TIMESTAMP_LTZ = 2014
        DPI_ORACLE_TYPE_INTERVAL_DS   = 2015
        DPI_ORACLE_TYPE_INTERVAL_YM   = 2016
        DPI_ORACLE_TYPE_CLOB          = 2017
        DPI_ORACLE_TYPE_NCLOB         = 2018
        DPI_ORACLE_TYPE_BLOB          = 2019
        DPI_ORACLE_TYPE_BFILE         = 2020
        DPI_ORACLE_TYPE_STMT          = 2021
        DPI_ORACLE_TYPE_BOOLEAN       = 2022
        DPI_ORACLE_TYPE_OBJECT        = 2023
        DPI_ORACLE_TYPE_LONG_VARCHAR  = 2024
        DPI_ORACLE_TYPE_LONG_RAW      = 2025
        DPI_ORACLE_TYPE_NATIVE_UINT   = 2026
        DPI_ORACLE_TYPE_MAX           = 2027
    end

    @enum dpiNativeTypeNum::UInt32 begin
        DPI_NATIVE_TYPE_INT64       = 3000
        DPI_NATIVE_TYPE_UINT64      = 3001
        DPI_NATIVE_TYPE_FLOAT       = 3002
        DPI_NATIVE_TYPE_DOUBLE      = 3003
        DPI_NATIVE_TYPE_BYTES       = 3004
        DPI_NATIVE_TYPE_TIMESTAMP   = 3005
        DPI_NATIVE_TYPE_INTERVAL_DS = 3006
        DPI_NATIVE_TYPE_INTERVAL_YM = 3007
        DPI_NATIVE_TYPE_LOB         = 3008
        DPI_NATIVE_TYPE_OBJECT      = 3009
        DPI_NATIVE_TYPE_STMT        = 3010
        DPI_NATIVE_TYPE_BOOLEAN     = 3011
        DPI_NATIVE_TYPE_ROWID       = 3012
    end

    @enum dpiStatementType::UInt16 begin
        DPI_STMT_TYPE_UNKNOWN      = 0
        DPI_STMT_TYPE_SELECT       = 1
        DPI_STMT_TYPE_UPDATE       = 2
        DPI_STMT_TYPE_DELETE       = 3
        DPI_STMT_TYPE_INSERT       = 4
        DPI_STMT_TYPE_CREATE       = 5
        DPI_STMT_TYPE_DROP         = 6
        DPI_STMT_TYPE_ALTER        = 7
        DPI_STMT_TYPE_BEGIN        = 8
        DPI_STMT_TYPE_DECLARE      = 9
        DPI_STMT_TYPE_CALL         = 10
        DPI_STMT_TYPE_EXPLAIN_PLAN = 15
        DPI_STMT_TYPE_MERGE        = 16
        DPI_STMT_TYPE_ROLLBACK     = 17
        DPI_STMT_TYPE_COMMIT       = 21
    end
end
